- nodes/platform_io.py
- Introduced the PlatformEnvs class with a method to define input types for environment selection (production, staging, develop).
- Implemented the execute method to retrieve organization ID and token based on the selected environment.
- Added constants for return types and names to facilitate integration with the platform I/O category.
> Add PlatformEnvs class for environment-specific organization credentials

- __init__.py
- nodes/lora.py
- nodes/web/lora.js
feat(nodes): Add new LoraStacker node with enhanced functionality
- Introduce new LoraStacker node supporting up to 10 LoRA slots
- Add Simple/Advanced weight control modes
- Implement per-slot enable/disable switches
- Mark old LoraStack node as deprecated
- Update node class mapping to support CLASS_NAME fallback
The new LoraStacker provides more flexibility and control over LoRA combinations,
replacing the limited 3-slot LoraStack implementation.
> Ml 105 implement row count selector for lora stacker node

- nodes/text.py
- Rename text input parameter to value for consistency
- Remove unnecessary STRING return type as node is output-only
- Remove OUTPUT_IS_LIST property
- Simplify return structure to only include UI output
> fix: Fix and Cleanup of Text Preview

- nodes/platform_io.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-359)
This PR uses the file type check from the parallel PR in signature-core. We still need to see how we can send a meaningful error message to the front-end when a user runs a workflow on the platform.
I tested with the following images, the first one is broken:
https://signature-eks-outputs-production.s3.eu-west-1.amazonaws.com/public/inputs/prod/301_1736955923392_0194279c-c1f1-7bf2-b68f-a1ade64ea022.png
https://signatureasset.s3.eu-west-1.amazonaws.com/signature-default/BackgroundRem.jpg
https://signature-eks-outputs-production.s3.eu-west-1.amazonaws.com/public/inputs/prod/289_1736955910047_0194279c-c1f1-7bf2-b68f-a1ade64ea022.png
https://www.gstatic.com/webp/gallery/1.webp
> ML-359: Add file type check for input image

- nodes/neurochain/clearml/report_scores.py
- nodes/neurochain/clearml/start_task.py
- nodes/neurochain/math/average.py
- nodes/utils.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-384)
This PR contains new nodes and node updates that I implemented when testing evaluations in ComfyUI (see Jira issue description for an example workflow). Specifically, we want to iterate over lists and collect outputs in a list again. I also needed some update of the ClearML nodes to report scores and data.
If we don't want to merge everything I can still select the parts that seem useful, let me know.
Example workflow: [Benchmark.json](https://github.com/user-attachments/files/18504070/Benchmark.json)
> ML-384: Add convenience nodes for iterations

- nodes/neurochain/agents/agent.py
- nodes/neurochain/evaluation/agent_evaluation.py
- nodes/neurochain/evaluation/bias_evaluation.py
- nodes/neurochain/evaluation/geval_evaluation.py
- nodes/neurochain/evaluation/json_correctness_evaluation.py
- nodes/neurochain/evaluation/prompt_alignment_evaluation.py
- nodes/neurochain/evaluation/summarization_evaluation.py
- nodes/neurochain/evaluation/toxicity_evaluation.py
- nodes/neurochain/neurochain_utils/lines_to_string_list.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-396)
This PR adds a node to evaluate a list of agents with a list of evaluations. You need to send a list of input prompts of the agent and a list of expected outputs. Optionally you can report the scores to ClearML. 
You will need the parallel PR of neurochain.
An example report in ClearML is here: https://app.ml-platform-clearml.signature.ai/projects/d7f6745177e44092b905ce96f5d164b5/experiments/f4dcc040709545b5843fbdbff56379d0/info-output/metrics/plots?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=
Example workflow: …
> ML-396: Add node run a list of evaluations for a list of agents

- nodes/neurochain/neurochain_utils/fill_template.py
- pyproject.toml
- tests/nodes/neurochain/neurochain_utils/test_fill_template.py
- uv.lock
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-410)
This PR adds support to fill a template with values from a nested dict. The convention to use nested keys in the template is `[key1.subkey1.subsubkey1]` and so on.
I also added tests to see if the code works. I did not find an easy way to run the tests out-of-the-box with pytest as we don't have a `src` folder. You can run the tests when you temporarily rename `__init__.py` to something else and just call `pytest`.
Example workflow: [TemplateFilling.json](https://github.com/user-attachments/files/18561842/TemplateFilling.json)
> ML-410: Update fill template to support nested dict

- nodes/models.py
- pyproject.toml
- uv.lock
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-154)
This PR adds an additional input to the MagicEraser for an upscale model. You need the parallel PR of signature-core to test this.
Example Workflow: [MagicEraserUpscale.json](https://github.com/user-attachments/files/18560497/MagicEraserUpscale.json)
> ML-154: Add optional upscale model input to MagicEraser

- nodes/neurochain/embeddings/get_embeddings.py
- nodes/web/get_embeddings.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-414)
This PR updates the Get Embedding node to support two more models besides resnet50: mini-lm-l6 for text embeddings and clip for image/text embeddings. I also updated the node so that it only shows the inputs/outputs that the model supports.
You will need the parallel PR in neurochain to test this.
Example workflow: [Embedding2.json](https://github.com/user-attachments/files/18589425/Embedding2.json)
> ML-414: Update embedding node to support more image/text models

- nodes/mask.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-183)
Implement a second output to SIG Mask Grow With Blur node which outputs the inverted mask based on the first output.
[worflow.json](https://github.com/user-attachments/files/18655438/Add.InvertMask.to.MaskGrowWithBlur.Workflow.json)
> feat: add inverted mask output to node

- nodes/image_processing.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-106)
Create a node that takes a certain megapixels value, calculates the desired Height and Width based on the calculations and resizes the image and/or mask based on the calculations.
[Resize with megapixels Workflow.json](https://github.com/user-attachments/files/18689267/Resize.with.megapixels.Workflow.json)
> feat: create node to resize images with megapixels

- nodes/web/all_nodes.js
- nodes/web/contextmenu.js
- nodes/web/setgetnodes.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-687)
This PR adds two nodes to Set and to Get values. It helps to make workflows cleaner, as there is no visible link. The user can choose to make the links visible (in the context menu). The links are also part of the internal graph and will be part of the prompt to execute the workflow.
Example workflow: [getset.json](https://github.com/user-attachments/files/19030121/getset.json)
> ML-678: Add nodes to set/get values

- nodes/web/helpers/metadata_editor/main.js
- nodes/web/helpers/metadata_editor/style.js
- nodes/web/helpers/metadata_editor/utils.js
- nodes/web/helpers/workflow/form.js
- nodes/web/helpers/workflow/main.js
- nodes/web/helpers/workflow/nodeOrder.js
- nodes/web/helpers/workflow/node_order/style.js
- nodes/web/helpers/workflow/node_order/utils.js
- nodes/web/metada_editor.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-676)
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-677)
Add metadata button to relevant nodes that opens a dialogue box with all the metadata fields and, if applicable, default/placeholders.
Metadata is now saved on the the metadata widget and a `signature_metadata` inside the `properties` key in the node.
Node order is now being saved on the `signature_metadata` object
https://github.com/user-attachments/assets/69ca3218-55f0-4594-9075-67b3ea85dbed
[metadata test.json](https://github.com/user-attachments/files/19364202/metadata.test.json)
> feat: add dialog option to manipulate metadata of relevant nodes

- nodes/core/platform/input_image.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-689)
Output shape of Input image node, when it's ran with subtype `mask`, now doesn't display the channels
Fixes # (SIGML-689)
> fix: remove image channels when subtype in input_image is mask

- nodes/core/image_processing/guided_random_crop.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-696)
add min and max crop size as input on guided random crop node.
the crop size is now randomised, for each crop, based on the given values
> feat: add random min and max crop size input to guided random crop node

- nodes/neurochain/dojo/create_training_run.py
- nodes/neurochain/dojo/start_training_run.py
In the new training pipeline we do not use the model version anymore. This needs an update of neurochain that is in a parallel PR. In neurochain there are more changes when we call the API, but for ComfyUI the relevant change is the model version.
> Remove model version in training

- nodes/web/helpers/metadata_editor/utils.js
- nodes/web/helpers/workflow/node_order/style.js
- nodes/web/helpers/workflow/node_order/utils.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-697)
Add signature Input Boolean to list of nodes with editable metadata
Add order change on metadata widget as well
> Hotfix release/2.1.4 sigml 697 input boolean node edit metadata option is missing for this type of input

- nodes/web/helpers/workflow/node_order/style.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-698)
Changed code so it doesn't assign a new value to a const in the node order
> fix: remove assignment of value to const on node order metadata

- nodes/core/platform/input_image.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-699)
get_BWHC function already returns a Tensor with 3 channels if it's a mask so no more logic needed
> fix: handle images where the shape has 3 indexes

- nodes/core/models/magic_eraser.py
[JIRA Issue](SIGML-625-magic-eraser-error)
Update condition to run model on magic eraser. Now it takes into account if the model being passed is also not `"None"`
Fixes # (SIGML-625)
> fix: update condition to run model on magic eraser node

- src/signature_nodes/core/platform/workflow_execution_metadata.py
- src/signature_nodes/neurochain/dojo/create_training_run.py
- src/signature_nodes/neurochain/dojo/start_training_run.py
- src/signature_nodes/shared.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-763)
This PR adds a global setting with a correlation ID. The correlation ID will be set by the workflow execution metadata. We also create a default ID, e.g. we can bypass the workflow execution metadata in local development and still have a correlation ID in the logs.
You need the paralllel PR of neurochain to test this.
Example workflow: [training.json](https://github.com/user-attachments/files/19779994/training.json)
> SIGML-763: Add global setting object with correlation ID
