signatureai/signature-nodes

- nodes/platform_io.py
Need custom output paths for ComfyUI sagemaker endpoints
> custom image output path

- nodes/augmentations.py
- nodes/shared.py
- nodes/utils.py
- nodes/web/logic.js
- nodes/web/signature.js
- nodes/web/wrapper.js
- Added detailed docstrings to all augmentation classes explaining functionality, parameters, and usage notes
- Added return names to utility nodes for better clarity
- Fixed name casing in web extension identifiers
- Added RGB<->Grayscale conversion utility nodes
- Added __ne__ method to AnyType class
> refactor: Improve overall code readability and documentation

- nodes/utils.py
- nodes/web/list_builder.js
feat: Add ListBuilder node and refine loop node connections
- Add new ListBuilder utility node for dynamic list creation with up to 10 slots
- Description of node's purpose and functionality
> Ml 45 batch list builder stacker

- .github/pull_request_template.md
- nodes/augmentations.py
When opening a PR, be sure to add labels if necessary:
- `patch`: patch version update (1.0.0 -> 1.0.1)
- `minor`: Minor version update (1.0.0 -> 1.1.0)
- `major`: Major version update, breaking changes (1.0.0 -> 2.0.0)
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
- 
First you'll need to add the relevant Docker metadata to the `.github/configs/experiments.yml` file; you'll need to add the `working_directory` (i.e the directory where the experiment's `Dockerfile` is located) and the full ECR repostitory name (`ecr_repository`)
You can trigger the various Github workflows by commenting the following commands on the PR:
- `docker push [experiment_name] [environment]`
- …
> Test basic publish

- nodes/web/signature.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
- 
Start your commit messages with one of the following keywords to trigger version updates:
> patch: hotfix signature.js

- .github/workflows/publish.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
- 
Start your commit messages with one of the following keywords to trigger version updates:
> new release config

- .github/pull_request_template.md
- .github/workflows/publish.yml
- .github/workflows/steps-post-comment.yml
- .isort.cfg
- __init__.py
- nodes/augmentations.py
- nodes/mask.py
- nodes/numbers.py
- nodes/shared.py
- nodes/text.py
- nodes/web/signature.js
- release.config.js
- services/signature_flow_service.py
- Added SignatureFlowService to handle workflow manifest creation and data retrieval.
- Improved import handling in __init__.py to check for availability of signature_core and signature_flows packages.
- Refactored shared constants (MAX_INT, MAX_FLOAT, BASE_COMFY_DIR, SIGNATURE_NODES_DIR) to be imported from the parent module for better organization.
- Updated mask.py and numbers.py to import constants from the shared module.
- Modified signature.js to improve error handling and logging during workflow operations.
- Cleaned up platform_io.py and shared.py by removing unnecessary code and imports.
> Ml 291 integrate signature flows workflow manifest on signature core nodes

- .editorconfig
- .isort.cfg
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- uv.lock
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-321)
This PR updates the project files to have a common set of settings across our repositories. I also updated the README to include `uv` as dependency manager.
> ML-321: Update project files

- nodes/neurochain/agents/florence2/florence2.py
- nodes/neurochain/utils.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-336)
This PR adds a local mode for the Florence2 node. The model will run on the local machine in this mode. The PR also contains a refactor as the logic for local and remote model inference is now part of neurochain.
You will need the parallel PR in neurochain to test this.
Workflow for testing: [Florence2local.json](https://github.com/user-attachments/files/18379877/Florence2local.json)
> ML-336: Add local mode for florence2 node

- nodes/neurochain/agents/audio/transcribe_audio.py
- nodes/neurochain/agents/florence2/florence2.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-352)
This PR adds a device parameter for the audio transcriber and the florence2 neurochain classes. We use the torch device of the ComfyUI model manager.
You need the parallel PR of neurochain to test this.
> ML-352: Add device parameter to florence2 and audio transcription

- nodes/neurochain/neurochain_utils/json_schema_builder.py
- nodes/web/json_schema_builder.js
This PR adds a node to create simple JSON schemas with field names, types and descriptions.
Workflow: [JsonSchemaBuilder.json](https://github.com/user-attachments/files/18456411/JsonSchemaBuilder.json)
> ML-308: Add node to build a JSON schema

- nodes/neurochain/agents/florence2/florence2.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-375)
This PR adds the attention parameter to the florence2 node.
You will need the parallel PR of neurochain to test this.
Workflow: [Florence2.json](https://github.com/user-attachments/files/18475671/Florence2.json)
> ML-375: Add attention parameter to florence2

- nodes/neurochain/agents/florence2/florence2.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-389)
This PR removes the brackets from the task tokens in the input list of the florence2 node.
Example workflow: [Florence2.json](https://github.com/user-attachments/files/18488330/Florence2.json)
> ML-389: Remove brackets from task_token in florence2

- .pre-commit-config.yaml
- nodes/neurochain/agents/audio/transcribe_audio.py
- nodes/neurochain/agents/florence2/florence2.py
- nodes/text.py
- nodes/web/signature.js
[JIRA Issue](https://signature-ai.atlassian.net/jira/software/projects/ML/boards/4?selectedIssue=ML-385)
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
- 
Start your commit messages with one of the following keywords to trigger version updates:
> Ml 385 add base workflow id to the workflow submition

- nodes/neurochain/agents/florence2/florence2.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-388)
This PR adds a precision input to the forence2 node. You can choose between float16, bfloat16 and float32.
You need the parallel PR of neurochain to test this.
Example workflow: [Florence2.json](https://github.com/user-attachments/files/18487938/Florence2.json)
> ML-388: Add precision input to florence2 node

- nodes/neurochain/document_loaders/text_from_pdf.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-377)
This PR adds a node to extract text from a PDF file.
You will need the parallel PR in neurochain to test this.
Example workflow: [PDF.json](https://github.com/user-attachments/files/18491491/PDF.json)
> ML-377: Add node to get text from a PDF file

- nodes/neurochain/agents/agent.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-395)
Allow single values as input to tools and images input in the agent node.
Example workflow: [ImageList.json](https://github.com/user-attachments/files/18508701/ImageList.json)
> ML-395: Accept single values for images and tools in agent node

- nodes/neurochain/agents/tools/websearch.py
This is a small fix for the return type of the websearch tool.
> fix: Use correct return type in websearch

- __init__.py
- utils.py
[JIRA Issue](https://signature-ai.atlassian.net/jira/software/projects/ML/boards/4?selectedIssue=ML-408)
I implemented a dynamic import process using concurrent tasks, reducing the execution time from 11 seconds to 3 seconds, this is important because on serverless jobs the startup speeds add up.
> Ml 408 speedup signature nodes dynamic import process

- nodes/data.py
- nodes/neurochain/neurochain_utils/any/any_to_dict.py
- nodes/neurochain/neurochain_utils/any/any_to_list.py
- nodes/neurochain/neurochain_utils/dicts/dict_key_value.py
- nodes/neurochain/utils.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-422)
Replaces the neurochain WILDCARD with any_type. This should fix the loading of the signature nodes when neurochain is not available.
> ML-422: Replace neurochain WILDCARD with any_type

- __init__.py
[[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-421?atlOrigin=eyJpIjoiN2U1NTc1MmEwYTgxNDU4Y2IwZWI5MTBmNjlhZDRiODUiLCJwIjoiaiJ9)]
Fixed issue where, upon initializing the server, errors were arising from trying to import neurochain and/or signature flows when they weren't present
Fixes # (ML-421)
> fix: fix neurochain initialization and dynamic imports

- pyproject.toml
- requirements.txt
- uv.lock
Please include a summary of the change and which issue is fixed. Please also include
relevant motivation and context.
-
Start your commit messages with one of the following keywords to trigger version
updates:
> add 'pygit2>=1.17.0'

- nodes/neurochain/agents/florence2/florence2.py
- nodes/web/florence2.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-505)
Instead of removing the output we now put a red cross next to the outputs that have no meaningful output for the selected task.
Example workflow: [Florence2Update.json](https://github.com/user-attachments/files/18658739/Florence2Update.json)
> ML-505: Mark outputs as disabled

- nodes/utils.py
- nodes/web/dynamic_input_amount.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-103)
Create a ComfyUI node that works similarly to the ListBuilder node. This will take an amount of images (max 10) and return a batch of those images.
[Workflow.json](https://github.com/user-attachments/files/18658529/Batch.Builder.Workflow.json)
> feat: create batch builder node

- scripts/generate_docs.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-554)
Documentation now has description of the node as a fallback, in case there's no docstring.
> feat: use description as fallback for documentation

- nodes/core/logic/do_while_loop_end.py
- nodes/core/logic/do_while_loop_start.py
- nodes/logic.py
- nodes/web/logic.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-528)
This PR renames the loop nodes to "Do While" loop nodes. I also deprecated the old loop nodes.
Example workflow: [ForLoop.json](https://github.com/user-attachments/files/18691207/ForLoop.json)
> ML-528: Rename loop nodes to while loops

- nodes/core/logic/do_while_loop_end.py
- nodes/core/logic/do_while_loop_start.py
- nodes/web/do_while_loop.js
- nodes/web/florence2.js
- nodes/web/logic.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-526)
This PR aligns the input/output management with the ListBuilder. I added a widet num_slots that allows the user to control the number of inputs and outputs.
Example workflow: [DoWhileLoopUpdate.json](https://github.com/user-attachments/files/18705449/DoWhileLoopUpdate.json)
> ML-526: Add num_slots for inputs and outputs in loop nodes

- nodes/logic.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-294)
Implement lazy input check on `Switch` node to prevent unwanted nodes to run.
> feat: implement check lazy status logic

- nodes/platform_io.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-570)
Change condition that made it so URL's with commas would be split to URL's separated by a single white space.
Fixes # ([issue](https://signature-ai.atlassian.net/browse/ML-570))
> fix: separate multiple URL with space instead of comma

- nodes/platform_io.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-568)
I removed all calls to `clean_memory()` from `platform_io.py`. This speeds up the workflow execution significantly. We do not need this anymore as the workflows are executed and cleaned in our new infrastructure.
> ML-568: Remove clean_memory calls

- nodes/web/signature.js
* Fetches workflows from QA environment to be displayed on the workflow submission form
* Authentication wrapper
> Workflow submission fetch from api

- nodes/categories.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-567)
This PR moves the Dojo category up one level from neurochain to the root Signature Nodes.
> ML-567: Move Dojo category up from neurochain to signature

- .github/workflows/steps-post-comment.yml
- README.md
Please include a summary of the change and which issue is fixed. Please also include
relevant motivation and context.
-
Start your commit messages with one of the following keywords to trigger version
updates:
> Test pytest

- .github/workflows/deploy.yml
[JIRA Issue](https://signature-ai.atlassian.net/jira/software/projects/ML/boards/4?selectedIssue=ML-613)
> chore: Improve version tag generation in deployment workflow

- .github/workflows/deploy.yml
> test deploy

- nodes/web/signature.js
- nodes/web/signature_api/main.js
- nodes/web/signature_api/workflow_services.js
- nodes/web/workflow.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-652)
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-593)
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-653)
Implement Open workflows from Signature Functionality.
User is able to see the list of workflows and, after selecting one, the list of available version to open in ComfyUI
Added extra functionality by defaulting the info of deploying to signature based on the uploaded workflow
https://github.com/user-attachments/assets/fff2dacc-e96a-4dc0-9813-621a45ed5983
> Feature/ml 593 improve UI for listing available workflows

- nodes/neurochain/dojo/create_training_run.py
Add two new inputs to the create training run node.
> Add new inputs to create training run node

- .github/workflows/deploy.yml
[JIRA Issue](https://signature-ai.atlassian.net/browse/ML-654)
This PR removes the tests from the github pipeline. We want to implement all logic in our libraries, so all tests will run there.
> ci: Remove tests from github pipeline

- .pre-commit-config.yaml
> update precommit config

- env.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-644)
This PR adds three environment variables for AWS as required. We need these as we use boto3 to get secrets.
> SIGML-644: Add AWS environment variables

- nodes/core/lora/save_lora_captions.py
- nodes/neurochain/dojo/build_lora_dataset.py
- nodes/neurochain/dojo/create_training_run.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-635)
Add logic for handling simple tuner to save lora captions node.
https://github.com/user-attachments/assets/19f9ec05-1588-424e-a2a3-f47679715df4
[save lora captions.json](https://github.com/user-attachments/files/19249047/save.lora.captions.json)
> Hotfix release/2.0.6

- nodes/neurochain/dojo/start_training_run.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-655)
This PR adds an input to the start training node that defines the training type ("aitoolkit" vs. "simpletuner").
To test this you need the parallel PR of neurochain.
> SIGML-655: Add training type input to start training node

- nodes/core/image_processing/guided_random_crop.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-675)
Create a node that given a image and a mask, samples random points inside the mask and returns random crops centered on each of the random points
[guided_ranodm_crop.json](https://github.com/user-attachments/files/19324059/guided_ranodm_crop.json)
> feat: create guided random crop node

- nodes/web/bug_report.js
- nodes/web/feature_request.js
- nodes/web/helpers/bug_report/main.js
- nodes/web/helpers/bug_report/style.js
- nodes/web/helpers/global/main.js
- nodes/web/helpers/global/utils.js
- nodes/web/helpers/workflow/form/style.js
- nodes/web/helpers/workflow/list/style.js
- nodes/web/helpers/workflow/node_order/style.js
- nodes/web/helpers/workflow/node_order/utils.js
- nodes/web/helpers/workflow/utils.js
- nodes/web/quality_checks/workflow/warning_dialogue.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-667)
Add add options of bug and feature request to dropdown menu.
Both options open a new tab with a JIRA Form to be filled.
https://github.com/user-attachments/assets/993f82e7-e08c-41a5-8f55-74ddc25c2b3f
> feat: add options of bug and feature request to dropdown menu

- nodes/core/data/get_image_list_item.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-680)
Fix return type of signature_get_image_list_item node
> fix: fix return type of signature_get_image_list_item node

- nodes/web/workflow.js
> refactor: remove unnecessary comment

- nodes/web/helpers/metadata_editor/main.js
- nodes/web/helpers/metadata_editor/style.js
- nodes/web/helpers/metadata_editor/utils.js
- nodes/web/helpers/workflow/form.js
- nodes/web/helpers/workflow/main.js
- nodes/web/helpers/workflow/nodeOrder.js
- nodes/web/helpers/workflow/node_order/style.js
- nodes/web/helpers/workflow/node_order/utils.js
- nodes/web/metada_editor.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-681)
Add signature_metadata and order to nodes if there isn't one already, when trying to order them
> fix: add signature_metadata to all nodes when trying to order them

- nodes/web/bug_report.js
- nodes/web/feature_request.js
- nodes/web/helpers/global/main.js
- nodes/web/helpers/global/utils.js
- nodes/web/helpers/workflow/node_order/utils.js
- nodes/web/helpers/workflow/utils.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-685)
Create a menu item for all Signature behaviours in ComfyUI
https://github.com/user-attachments/assets/4743bd31-f15b-4e91-b557-b08c9ae310d5
> feat: create a menu item to contain all signature features

- nodes/neurochain/dojo/build_lora_dataset.py
- nodes/neurochain/dojo/create_training_run.py
- pyproject.toml
- uv.lock
This PR adds support for cover image upload to the create training node. We will use the first image of the lora dataset from the build lora dataset node.
This PR needs the parallel PR in neurochain.
> Add support for cover image upload in training

- nodes/core/platform/input_image.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-700)
> fix: input image already returns a length 3 mask with get_BWHC() func

- nodes/web/helpers/workflow/node_order/utils.js
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-725)
Implemented proper handling of the clamp option in metadata
Fixes # (SIGML-725)
> fix: improve handling of clamp in metadata

- nodes/core/mask/mask_area.py
[JIRA Issue](https://signature-ai.atlassian.net/browse/SIGML-714)
Create a node to measure the area of a mask
> feat: create node to measure mask area

- nodes/web/helpers/workflow/form/style.js
- nodes/web/helpers/workflow/form/utils.js
[JIRA Issue](SIGML-740-add-required-on-title-description-and-cover-image-to-workflow-submission-on-comfy-ui)
Add validation to check for mandatory fields on submitting form.
Now the requirement for a workflow to have a title, description and cover image is visible on the FE.
> Feature/sigml 740 add required on title description and cover image to workflow submission on comfy UI

- pyproject.toml
Please include a summary of the change and which issue is fixed. Please also include
relevant motivation and context.
-
Start your commit messages with one of the following keywords to trigger version
updates:
> feat: update neurochain version

- src/signature_nodes/core/image/load_image_from_url.py
[JIRA Issue](SIGML-761-add-load-image-from-url-signature-nodes)
Add custom node to download pictures from a specified url
> feat: add custom node to download images from url

- pyproject.toml
- uv.lock
Update Signature-Flows dependacy
> chore: update signature-flows version to 1.3.2
